# -*- coding: utf-8 -*-
"""Join.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1697HZuy-hj4hlPmhhGcbgLWftGWQje7g
"""

import pandas as pd
import numpy as np

!wget https://raw.githubusercontent.com/Cynamon224/_Join/dev/factbook.csv

"""I downloaded dataset from https://perso.telecom-paristech.fr/eagan/class/igr204/datasets """

df=pd.read_csv('factbook.csv',sep=";")
df = df.drop(labels=0, axis=0)
df.head(10)

"""It isn't perfect data to work on for joining files but it was the best I found.

I split the data on two data frame to merge them together later.
"""

DF1=df.filter(['Country', 'Area(sq km)', 'Birth rate(births/1000 population)',
       'Current account balance', 'Death rate(deaths/1000 population)',
       'Debt - external', ])
DF2=df.filter(['Country','Military expenditures - dollar figure',
       'Military expenditures - percent of GDP(%)',
       'Natural gas - consumption(cu m)'])

"""I saved this two df to .csv files, because we need path for program to work"""

DF1.to_csv('DF1.csv', encoding = 'utf-8-sig',index=False) 
DF2.to_csv('DF2.csv', encoding = 'utf-8-sig',index=False)

def join(path1,path2,columnName,join):

  try:
    df1=pd.read_csv(path1)
  except:
    print("Wrong path1")
  try:
    df2=pd.read_csv(path2)
  except:
    print("Wrong path2")

  col1=list(df1.columns)
  col2=list(df2.columns)

  if columnName not in col1:
    print("This column name doesn't exist in file1")
    return
  if columnName not in col2:
    print("This column name doesn't exist in file2")
    return

  dfNew=pd.DataFrame
  join=join.strip().lower()

  if(join=="left"):
    dfNew=pd.merge(df1,df2,how="left",left_on=columnName,right_on=columnName)
  elif(join=="right"):
    dfNew=pd.merge(df1,df2,how="right",left_on=columnName,right_on=columnName)
  elif(join=="inner"):
    dfNew=pd.merge(df1,df2,how="inner",left_on=columnName,right_on=columnName)
  else:
    dfNew=pd.merge(df1,df2,how="outer",left_on=columnName,right_on=columnName)
  return dfNew

"""I understood the assignment that I should add print(dfNew.head()) in function but I don't like the way it shows records so I did it outside the function."""

df_inner=join("DF1.csv","DF2.csv","Country","inner")
df_inner.head()

"""The join type parameter isn't case-sensitive and it ignores white space."""

df_right=join("DF1.csv","DF2.csv","Country","Right")
df_right.head()

df_left=join("DF1.csv","DF2.csv","Country"," LeFt ")
df_left.head()

"""Outer type join is default type."""

df_outer=join("DF1.csv","DF2.csv","Country"," doesn't matter it will be outer ")
df_outer.head()

"""The data isn't perfect because there is no visible change to the dataframe whatever type of join we do. But I don't think it is a big problem because we use pandas function so there shouldn't be any errors (only when is something wrong with data)."""